### PR TITLE
New: corpseManagerMode attribute added.

### PR DESCRIPTION
**Pull request by EM-Creations**
Update: Improved documentation of various description.hpp settings for 
mission makers.

### CODE REVIEW

**Comment by EM-Creations** [comment]
This has been previously requested by members of the community, after seeing bodies disappearing on missions and not knowing how to resolve it etc..

**Comment by PiZZAD0X** [comment]
should the default be 1 or 0?
what about `wreckManagerMode` and the various time settings?

maybe an included file in the customization folder for these cleanup settings

**Comment by EM-Creations** [comment]
> should the default be 1 or 0?
> what about `wreckManagerMode` and the various time settings?
> 
> maybe an included file in the customization folder for these cleanup settings

0 means that all corspes are left, which I assume is what people want for "immersion", if you think that's too intensive though we could switch it to 2 and explain to people when they come asking just to change this variable?

I'll add wreckManagerMode and what are you thoughts about the default for that too?

**Comment by PiZZAD0X** [comment]
I think the defaults in the edit are good, and the standalone file in customization is very good

**Pull request merged**
