### PR TITLE
Remove: UO classlist, it goes to dead URL anyway.

### PR DESCRIPTION
**Pull request by EM-Creations**
As per title.

### CODE REVIEW

**Comment by PiZZAD0X** [comment]
we could remove the utility folder entirely, users should head to the github wiki and we can add info there that will update. The gear export script for olsen can be placed in core modules and called via the editor

**Comment by EM-Creations** [comment]
> we could remove the utility folder entirely, users should head to the github wiki and we can add info there that will update. The gear export script for olsen can be placed in core modules and called via the editor

Does anyone use the gearExport.sqf script which lives in there though?

**Comment by PiZZAD0X** [comment]
most people just copy over classnames

**Comment by EM-Creations** [comment]
> most people just copy over classnames

If they want it I guess they could just extract it from a previous commit or the old framework.

**Comment by PiZZAD0X** [comment]
we can have it in the core functions, FW_fnc_exportOlsenGear or something

**Comment by EM-Creations** [comment]
Now doing this piece of work here: https://github.com/Bear-Cave-ArmA/Olsen-Framework-Arma-3/pull/17

**Pull request closed without merging**
