### PR TITLE
Update: Default colour of the cover map changed from black to grey.

### PR DESCRIPTION
**Pull request by EM-Creations**
Having tested this module re-write I think it would be a better idea to make the default cover map colour grey instead of black. I find black quite straining, grey is much more neutral and I think would be better for the majority of people. I've attached a comparison.

black-bg
grey-bg

### CODE REVIEW

**Comment by PiZZAD0X** [comment]
@Bear-Cave-ArmA/olsen-framework Opinions?

**Comment by EM-Creations** [comment]
Other colours are here: https://community.bistudio.com/wiki/Arma_3_CfgMarkerColors

I just certainly don't think it should be black.

**Comment by VyMajoris** [comment]
... The mission maker should be able to change the color via the module settings.sqf.

**Comment by EM-Creations** [comment]
> ... The mission maker should be able to change the color via the module settings.sqf.

Yes they can if they wish. This is to change the DEFAULT colour. The colour to be used if no specific colour is provided. I have a feeling most people will not change it from the default colour hence why I believe its important that the default colour is carefully considered.

**Comment by PiZZAD0X** [comment]
We could set it with a color array rgba instead of the cfgmarkercolors.

**Comment by EM-Creations** [comment]
> We could set it with a color array rgba instead of the cfgmarkercolors.

Truthfully I think that may make it overly complicated for mission makers. @VyMajoris showed me a screenshot of a dark grey (in between black and the ligher grey shown) that he prefers.

**Comment by PiZZAD0X** [comment]
I would prefer the darker grey as well, there is `BH_checkLOS_colorNotVisible` 

Screenshot_1698

**Comment by EM-Creations** [comment]
> BH_checkLOS_colorNotVisible

OK thanks I'll sort this shortly.

**Comment by EM-Creations** [comment]
> > BH_checkLOS_colorNotVisible
> 
> OK thanks I'll sort this shortly.

@PiZZAD0X  done.

**Pull request merged**
